-- Generated by Oracle SQL Developer Data Modeler 18.4.0.339.1536
--   at:        2019-09-26 16:11:47 AEST
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c

-- Student ID - 30535808
-- Student Name - Anmol Sanjay Bagati

SET ECHO ON
SPOOL tds_schema_output.txt
DROP TABLE ENGINE_TYPE CASCADE CONSTRAINTS;
DROP TABLE MODEL CASCADE CONSTRAINTS;
DROP TABLE MANUFACTURER CASCADE CONSTRAINTS;
DROP TABLE MANUFACTURER_COUNTRY CASCADE CONSTRAINTS;
DROP TABLE SUSPENSION CASCADE CONSTRAINTS;
DROP TABLE LICENSE_TYPE CASCADE CONSTRAINTS;
DROP TABLE DRIVER CASCADE CONSTRAINTS;
DROP TABLE CLASSIFICATION CASCADE CONSTRAINTS;
DROP TABLE VEHICLE CASCADE CONSTRAINTS;
DROP TABLE VEHICLE_REGISTRATION CASCADE CONSTRAINTS;
DROP TABLE CANCELLATION CASCADE CONSTRAINTS;
DROP TABLE OFFENCE CASCADE CONSTRAINTS;
DROP TABLE OFFICER CASCADE CONSTRAINTS;
DROP TABLE DEMERIT CASCADE CONSTRAINTS;
DROP TABLE STATION CASCADE CONSTRAINTS;
DROP TABLE ASSIGNMENT_HISTORY CASCADE CONSTRAINTS;


CREATE TABLE assignment_history ( 
--  assignment start date
    assignment_start_date   DATE NOT NULL,
    officer_id              VARCHAR2(20) NOT NULL,
    station_no              VARCHAR2(20) NOT NULL
);

ALTER TABLE assignment_history ADD CONSTRAINT assignment_history_pk PRIMARY KEY ( assignment_start_date,
                                                                                  officer_id );

CREATE TABLE cancellation (
    cancellation_date        DATE NOT NULL, 
--  reason of license cancellation
    cancellation_reason      VARCHAR2(50) NOT NULL, 
--  date of court hearing
    court_hearing_date       DATE, 
--  date of license reinstation
    license_reinstate_date   DATE,
    license_no               CHAR(7) NOT NULL
);

COMMENT ON COLUMN cancellation.cancellation_date IS
    'date of cancellation';

COMMENT ON COLUMN cancellation.cancellation_reason IS
    'reason of license cancellation';

ALTER TABLE cancellation ADD CONSTRAINT cancellation_pk PRIMARY KEY ( cancellation_date,
                                                                      license_no );

CREATE TABLE classification (
    type_id                CHAR(4) NOT NULL,
    classicifaction_type   VARCHAR2(15) NOT NULL
);

COMMENT ON COLUMN classification.type_id IS
    'Unique type identification';

COMMENT ON COLUMN classification.classicifaction_type IS
    'type of license';

ALTER TABLE classification ADD CONSTRAINT classification_pk PRIMARY KEY ( type_id );

ALTER TABLE classification ADD CONSTRAINT classification_type UNIQUE ( classicifaction_type );

CREATE TABLE demerit (
    demerit_code           VARCHAR2(20) NOT NULL,
    demerit_description    VARCHAR2(75) NOT NULL,
    demerit_points         NUMBER(2),
    cancellation_trigger   CHAR(5) NOT NULL,
    cancellation_period    NUMBER(2)
);

ALTER TABLE demerit
    ADD CONSTRAINT chk_cancellation_trigger CHECK ( cancellation_trigger IN (
        'FALSE',
        'TRUE'
    ) );

COMMENT ON COLUMN demerit.demerit_code IS
    'demerit code';

COMMENT ON COLUMN demerit.demerit_description IS
    'Description of demerit';

COMMENT ON COLUMN demerit.demerit_points IS
    'demerit points';

COMMENT ON COLUMN demerit.cancellation_trigger IS
    'triggers cancellation during serious offences';

COMMENT ON COLUMN demerit.cancellation_period IS
    'period for which license wil be cancelled in months';

ALTER TABLE demerit ADD CONSTRAINT demerit_pk PRIMARY KEY ( demerit_code );

CREATE TABLE driver (
    license_no             CHAR(7) NOT NULL,
    license_status         CHAR(8) NOT NULL,
    driver_first_name      VARCHAR2(25) NOT NULL,
    driver_last_name       VARCHAR2(25) NOT NULL,
    driver_street          VARCHAR2(20) NOT NULL,
    driver_town            VARCHAR2(20) NOT NULL,
    driver_postcode        NUMBER(4) NOT NULL,
    driver_dob             DATE NOT NULL,
    license_expiry_date    DATE NOT NULL,
    total_demerit_points   NUMBER(2),
    offence_no             VARCHAR2(20) NOT NULL
);

ALTER TABLE driver
    ADD CONSTRAINT chk_license_status CHECK ( license_status IN (
        'Active',
        'Cancelled',
        'Inactive',
        'Suspended'
    ) );

ALTER TABLE driver
    ADD CONSTRAINT chk_total_demerit_points CHECK ( total_demerit_points BETWEEN 0 AND 12 );

COMMENT ON COLUMN driver.license_no IS
    'license identification number';

COMMENT ON COLUMN driver.license_status IS
    'license status';

COMMENT ON COLUMN driver.driver_first_name IS
    'Diver''s first name';

COMMENT ON COLUMN driver.driver_last_name IS
    'Driver''s last name';

COMMENT ON COLUMN driver.driver_street IS
    'driver''s street address';

COMMENT ON COLUMN driver.driver_town IS
    'driver''s town address';

COMMENT ON COLUMN driver.driver_postcode IS
    'driver''s postcode';

COMMENT ON COLUMN driver.driver_dob IS
    'driver''s date of birth';

COMMENT ON COLUMN driver.license_expiry_date IS
    'license expiry date';

COMMENT ON COLUMN driver.total_demerit_points IS
    'total number of demerit points accumulated by the driver as of date';

ALTER TABLE driver ADD CONSTRAINT driver_pk PRIMARY KEY ( license_no );

CREATE TABLE engine_type (
    engine_type     CHAR(8) NOT NULL, 
--  model of the vehicle
    vehicle_model   VARCHAR2(50) NOT NULL
);

ALTER TABLE engine_type
    ADD CONSTRAINT chk_engine_type CHECK ( engine_type IN (
        'Deisel',
        'Electric',
        'Gas',
        'Petrol'
    ) );

COMMENT ON COLUMN engine_type.engine_type IS
    'engine type';

ALTER TABLE engine_type ADD CONSTRAINT engine_pk PRIMARY KEY ( engine_type,
                                                               vehicle_model );

CREATE TABLE license_type (
    type_id      CHAR(4) NOT NULL,
    license_no   CHAR(7) NOT NULL
);

ALTER TABLE license_type ADD CONSTRAINT license_type_pk PRIMARY KEY ( type_id,
                                                                      license_no );

CREATE TABLE manufacturer ( 
--  manufacturere code
    manufacturer_code           CHAR(2) NOT NULL,
    manufacturer_name           VARCHAR2(20) NOT NULL,
    manufacturer_country_code   CHAR(3) NOT NULL
);

COMMENT ON COLUMN manufacturer.manufacturer_code IS
    'manufacturer code';

COMMENT ON COLUMN manufacturer.manufacturer_name IS
    'manufacturer name';

ALTER TABLE manufacturer ADD CONSTRAINT manufacturer_pk PRIMARY KEY ( manufacturer_code );

CREATE TABLE manufacturer_country (
    manufacturer_country_code   CHAR(3) NOT NULL,
    manufacturer_country_name   VARCHAR2(20) NOT NULL
);

COMMENT ON COLUMN manufacturer_country.manufacturer_country_code IS
    'manufacturer''s country code';

COMMENT ON COLUMN manufacturer_country.manufacturer_country_name IS
    'manufacturer''s country name';

ALTER TABLE manufacturer_country ADD CONSTRAINT manufacturer_country_pk PRIMARY KEY ( manufacturer_country_code );

CREATE TABLE model ( 
--  model of the vehicle
    vehicle_model          VARCHAR2(50) NOT NULL, 
--  transmission gear type
    transmission_type      VARCHAR2(10) NOT NULL, 
--  size of engine in litres
    engine_size            NUMBER(2, 1) NOT NULL, 
--  ground clearance laden
    gr_clearance_laden     NUMBER(3) NOT NULL, 
--  ground clearance unladen
    gr_clearance_unladen   NUMBER(3) NOT NULL,
    manufacturer_code      CHAR(2) NOT NULL
);

ALTER TABLE model
    ADD CONSTRAINT chk_transmission_type CHECK ( transmission_type IN (
        'Automatic',
        'Manual'
    ) );

COMMENT ON COLUMN model.vehicle_model IS
    'vehicle model name';

COMMENT ON COLUMN model.transmission_type IS
    'transmission type (manual or automatic)';

COMMENT ON COLUMN model.engine_size IS
    'engine size litre';

COMMENT ON COLUMN model.gr_clearance_laden IS
    'laden ground clearance';

COMMENT ON COLUMN model.gr_clearance_unladen IS
    'unladen ground clearance';

ALTER TABLE model ADD CONSTRAINT model_pk PRIMARY KEY ( vehicle_model );

CREATE TABLE offence (
    offence_no         VARCHAR2(20) NOT NULL,
    offence_location   VARCHAR2(50) NOT NULL,
    offence_datetime   DATE NOT NULL,
    offence_time       DATE NOT NULL,
    officer_id         VARCHAR2(20) NOT NULL,
    demerit_code       VARCHAR2(20) NOT NULL,
    vehicle_vin        CHAR(17) NOT NULL
);

COMMENT ON COLUMN offence.offence_no IS
    'Offence number';

COMMENT ON COLUMN offence.offence_location IS
    'location of the offence';

COMMENT ON COLUMN offence.offence_datetime IS
    'date of the offence';

COMMENT ON COLUMN offence.offence_time IS
    'date of the offence';

ALTER TABLE offence ADD CONSTRAINT offence_pk PRIMARY KEY ( offence_no );

CREATE TABLE officer (
    officer_id           VARCHAR2(20) NOT NULL,
    officer_first_name   VARCHAR2(15) NOT NULL,
    officer_last_name    VARCHAR2(15) NOT NULL,
    officer_rank         VARCHAR2(20) NOT NULL
);

COMMENT ON COLUMN officer.officer_id IS
    'unique officer identification ';

COMMENT ON COLUMN officer.officer_first_name IS
    'officer''s first name';

COMMENT ON COLUMN officer.officer_last_name IS
    'officer''s last name';

COMMENT ON COLUMN officer.officer_rank IS
    'officer rank';

ALTER TABLE officer ADD CONSTRAINT officer_pk PRIMARY KEY ( officer_id );

CREATE TABLE station (
    station_no            VARCHAR2(20) NOT NULL,
    station_address       VARCHAR2(75) NOT NULL,
    station_contact_no    CHAR(10) NOT NULL,
    station_open_status   VARCHAR2(10) NOT NULL,
    officer_id            VARCHAR2(20) NOT NULL
);

COMMENT ON COLUMN station.station_no IS
    'unique station number';

COMMENT ON COLUMN station.station_address IS
    'address of the station';

COMMENT ON COLUMN station.station_contact_no IS
    'contatc number of the station';

COMMENT ON COLUMN station.station_open_status IS
    'if station is open 24*7 or not';

CREATE UNIQUE INDEX station__idx ON
    station (
        officer_id
    ASC );

ALTER TABLE station ADD CONSTRAINT station_pk PRIMARY KEY ( station_no );

CREATE TABLE suspension ( 
--  start date of suspension
    suspension_start_date   DATE NOT NULL, 
--  end date of suspension
    suspension_end_date     DATE NOT NULL,
    license_no              CHAR(7) NOT NULL
);

COMMENT ON COLUMN suspension.suspension_start_date IS
    'suspension start date';

COMMENT ON COLUMN suspension.suspension_end_date IS
    'suspension end date';

ALTER TABLE suspension ADD CONSTRAINT license_suspension_pk PRIMARY KEY ( suspension_start_date,
                                                                          license_no );

CREATE TABLE vehicle (
    vehicle_vin               CHAR(17) NOT NULL,
    vehicle_manfacture_year   NUMBER(4) NOT NULL,
    vehicle_colour            VARCHAR2(15) NOT NULL,
    vehicle_model             VARCHAR2(50) NOT NULL,
    type_id                   CHAR(4) NOT NULL
);

COMMENT ON COLUMN vehicle.vehicle_vin IS
    'vehicle identification number';

COMMENT ON COLUMN vehicle.vehicle_manfacture_year IS
    'vehicle manufacture year';

COMMENT ON COLUMN vehicle.vehicle_colour IS
    'colour of the vehicle';

ALTER TABLE vehicle ADD CONSTRAINT vehicle_pk PRIMARY KEY ( vehicle_vin );

CREATE TABLE vehicle_registration (
    vehicle_reg_date     DATE NOT NULL,
    vehicle_reg_no       CHAR(6) NOT NULL,
    vehicle_dereg_date   DATE,
    vehicle_vin          CHAR(17) NOT NULL
);

COMMENT ON COLUMN vehicle_registration.vehicle_reg_date IS
    'vehicle registration date';

COMMENT ON COLUMN vehicle_registration.vehicle_reg_no IS
    'vehicle registration number';

COMMENT ON COLUMN vehicle_registration.vehicle_dereg_date IS
    'vehicle de-registration date';

ALTER TABLE vehicle_registration ADD CONSTRAINT vehicle_registration_pk PRIMARY KEY ( vehicle_reg_date,
                                                                                      vehicle_vin );

ALTER TABLE license_type
    ADD CONSTRAINT classification_license FOREIGN KEY ( type_id )
        REFERENCES classification ( type_id );

ALTER TABLE vehicle
    ADD CONSTRAINT classification_vehicle FOREIGN KEY ( type_id )
        REFERENCES classification ( type_id );

ALTER TABLE cancellation
    ADD CONSTRAINT driver_cancellation FOREIGN KEY ( license_no )
        REFERENCES driver ( license_no );

ALTER TABLE license_type
    ADD CONSTRAINT driver_license FOREIGN KEY ( license_no )
        REFERENCES driver ( license_no );

ALTER TABLE driver
    ADD CONSTRAINT driver_offence FOREIGN KEY ( offence_no )
        REFERENCES offence ( offence_no );

ALTER TABLE suspension
    ADD CONSTRAINT driver_suspension FOREIGN KEY ( license_no )
        REFERENCES driver ( license_no );

ALTER TABLE manufacturer
    ADD CONSTRAINT manufacturer_country FOREIGN KEY ( manufacturer_country_code )
        REFERENCES manufacturer_country ( manufacturer_country_code );

ALTER TABLE model
    ADD CONSTRAINT manufacturer_vehicle FOREIGN KEY ( manufacturer_code )
        REFERENCES manufacturer ( manufacturer_code );

ALTER TABLE engine_type
    ADD CONSTRAINT model_engine FOREIGN KEY ( vehicle_model )
        REFERENCES model ( vehicle_model );

ALTER TABLE vehicle
    ADD CONSTRAINT model_vehicle FOREIGN KEY ( vehicle_model )
        REFERENCES model ( vehicle_model );

ALTER TABLE offence
    ADD CONSTRAINT offence_demerit FOREIGN KEY ( demerit_code )
        REFERENCES demerit ( demerit_code );

ALTER TABLE assignment_history
    ADD CONSTRAINT officer_assignment FOREIGN KEY ( officer_id )
        REFERENCES officer ( officer_id );

ALTER TABLE offence
    ADD CONSTRAINT officer_offence FOREIGN KEY ( officer_id )
        REFERENCES officer ( officer_id );

ALTER TABLE station
    ADD CONSTRAINT officer_station FOREIGN KEY ( officer_id )
        REFERENCES officer ( officer_id );

ALTER TABLE assignment_history
    ADD CONSTRAINT station_assignment FOREIGN KEY ( station_no )
        REFERENCES station ( station_no );

ALTER TABLE offence
    ADD CONSTRAINT vehicle_offence FOREIGN KEY ( vehicle_vin )
        REFERENCES vehicle ( vehicle_vin );

ALTER TABLE vehicle_registration
    ADD CONSTRAINT vehicle_registration FOREIGN KEY ( vehicle_vin )
        REFERENCES vehicle ( vehicle_vin );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            16
-- CREATE INDEX                             1
-- ALTER TABLE                             39
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
